"""
Repository module for Job entity database operations.

This module acts as the Data Access Layer (DAL) for the 'jobs' table in
PostgreSQL, utilizing `asyncpg` for high-performance asynchronous I/O.
It provides atomic state transitions and bulk state flushing essential
for the MapReduce orchestration pipeline, ensuring ACID-compliant consistency
across distributed, highly concurrent worker components.
"""

import logging
import uuid
from typing import Any, Dict, List, Optional

import asyncpg
from fastapi import HTTPException

from app.models.domain import Job

# Initialize the module-level logger for persistent state events and telemetry
logger = logging.getLogger(__name__)


class JobRepository:
    """
    Data Access Object (DAO) for Job records and distributed state transitions.

    This class provides static, stateless methods to interface with the PostgreSQL
    persistence layer. It leverages raw SQL for optimized query planning and handles
    everything from optimistic concurrency control during job scheduling to
    granular progress aggregation and stalled job reclamation.
    """

    @staticmethod
    async def create_job(
            job_id: str,
            user_id: str,
            file_format: str,
            input_filename: str,
            mapper_filename: str,
            reducer_filename: str,
            db_pool: asyncpg.Pool,
            num_mappers: Optional[int] = None,
            num_reducers: Optional[int] = None
    ) -> Job:
        """
        Creates a new MapReduce job record with an initial state of 'SUBMITTED'.

        This method performs the synchronous initial database write before the
        Orchestrator publishes the workload to the message broker.

        :param job_id: The universally unique identifier (UUID) generated by the API.
        :type job_id: str
        :param user_id: The UUID of the tenant submitting the job.
        :type user_id: str
        :param file_format: The data serialization format (e.g., 'JSON', 'TEXT', 'AVRO').
        :type file_format: str
        :param input_filename: The S3 key/path to the raw input data.
        :type input_filename: str
        :param mapper_filename: The S3 key/path to the compiled Mapper class.
        :type mapper_filename: str
        :param reducer_filename: The S3 key/path to the compiled Reducer class.
        :type reducer_filename: str
        :param db_pool: The shared, multiplexed PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :param num_mappers: Optional explicit override for Map worker parallelism.
        :type num_mappers: Optional[int]
        :param num_reducers: Optional explicit override for Reduce partitions.
        :type num_reducers: Optional[int]
        :return: A domain model instance representing the newly inserted record.
        :rtype: Job
        """
        query = """
                INSERT INTO public.jobs (id, user_id, status, format, input_filename, mapper_filename, reducer_filename, \
                                         num_mappers, num_reducers)
                VALUES ($1, $2, 'SUBMITTED', $3, $4, $5, $6, $7, $8) RETURNING *; \
                """

        async with db_pool.acquire() as connection:
            record = await connection.fetchrow(
                query,
                uuid.UUID(str(job_id)),
                uuid.UUID(str(user_id)),
                file_format,
                input_filename,
                mapper_filename,
                reducer_filename,
                num_mappers,
                num_reducers
            )

            logger.info("Synchronously created new job %s in SUBMITTED state.", job_id)
            return Job(**dict(record))

    @staticmethod
    async def transition_job_to_running(
            job_id: str,
            total_chunks: int,
            num_reducers: int,
            db_pool: asyncpg.Pool,
            num_mappers: Optional[int] = None
    ) -> Job:
        """
        Atomically updates a job's status to 'RUNNING' using optimistic concurrency.

        This method performs a single-trip atomic update, transitioning the state machine
        while simultaneously locking in the derived partition metrics and explicit
        pod overrides. The `AND status = 'SUBMITTED'` clause ensures that concurrent
        scheduling requests for the same job ID (e.g., due to network retries) do not
        corrupt the running state.

        :param job_id: The unique universally unique identifier (UUID) of the job.
        :type job_id: str
        :param total_chunks: The calculated total number of Map tasks to be processed.
        :type total_chunks: int
        :param num_reducers: The calculated count of Reduce partitions to provision.
        :type num_reducers: int
        :param db_pool: The shared, multiplexed PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :param num_mappers: Optional explicit override for Map worker parallelism.
        :type num_mappers: Optional[int]
        :return: A domain model instance representing the successfully mutated record.
        :rtype: Job
        :raises HTTPException: 404 error if the job does not exist, or if it has
            already transitioned out of the 'SUBMITTED' state.
        """
        update_query = """
                       UPDATE public.jobs
                       SET status       = 'RUNNING',
                           total_chunks = $1,
                           num_reducers = $3,
                           num_mappers  = $4
                       WHERE id = $2 
                         AND status = 'SUBMITTED' RETURNING *; 
                       """
        async with db_pool.acquire() as connection:
            record = await connection.fetchrow(
                update_query,
                total_chunks,
                uuid.UUID(str(job_id)),
                num_reducers,
                num_mappers
            )
            if not record:
                logger.error("Failed status transition: Job %s not found or not SUBMITTED. Possible duplicate schedule request.", job_id)
                raise HTTPException(
                    status_code=404,
                    detail=f"Job {job_id} not found or is already in progress."
                )

            # Contextual telemetry logging based on scaling strategy
            if num_mappers:
                logger.info("Successfully transitioned job to RUNNING with %s explicit mappers and %s reducers.", num_mappers, num_reducers)
            else:
                logger.info("Successfully transitioned job to RUNNING with auto-scaled mappers and %s reducers.", num_reducers)

            return Job(**dict(record))

    @staticmethod
    async def get_job_metadata(job_id: str, db_pool: asyncpg.Pool) -> Optional[Dict[str, Any]]:
        """
        Retrieves read-only execution metadata for a specific job.

        Architecture Context:
        This query isolates the retrieval of `user_id` and the specific `reducer_filename`
        to construct secure, multi-tenant S3 path boundaries downstream. Reflection-based
        class names are intentionally omitted, delegating bytecode localization entirely
        to the isolated Sandbox runtime.

        :param job_id: The UUID of the target job.
        :type job_id: str
        :param db_pool: The shared PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :return: Job metadata dictionary, or None if the job identifier is invalid.
        :rtype: Optional[Dict[str, Any]]
        """
        query = """
            SELECT user_id, total_chunks, reducer_filename, num_reducers
            FROM public.jobs
            WHERE id = $1;
        """
        async with db_pool.acquire() as connection:
            record = await connection.fetchrow(query, uuid.UUID(str(job_id)))

            # Transform the asyncpg Record object into a JSON-serializable dictionary
            return {str(k): v for k, v in record.items()} if record else None

    @staticmethod
    async def flush_map_phase(job_id: str, total_completed: int, db_pool: asyncpg.Pool) -> None:
        """
        Executes a bulk persistence operation for Map phase progress.

        Rather than issuing high-frequency database writes per task completion,
        progress is aggregated in memory (via Redis Lua barriers) and flushed
        here collectively to mitigate connection pool saturation and IOPS bottlenecks.
        """
        query = """
            UPDATE public.jobs
            SET completed_map_chunks = $1
            WHERE id = $2 
              AND status != 'COMPLETED';
        """
        async with db_pool.acquire() as connection:
            await connection.execute(query, total_completed, uuid.UUID(str(job_id)))
        logger.info("Persisted Map phase barrier to DB: %s chunks.", total_completed)

    @staticmethod
    async def flush_reduce_phase(job_id: str, total_completed: int, db_pool: asyncpg.Pool) -> None:
        """
        Executes a bulk persistence operation for Reduce phase progress.

        Aggregates partition completion signals to update the persistent state store,
        safeguarded against modifying jobs that have already reached terminal states.
        """
        query = """
            UPDATE public.jobs
            SET completed_reduce_chunks = $1
            WHERE id = $2 
              AND status != 'COMPLETED';
        """
        async with db_pool.acquire() as connection:
            await connection.execute(query, total_completed, uuid.UUID(str(job_id)))
        logger.info("Persisted Reduce phase barrier to DB: %s partitions.", total_completed)

    @staticmethod
    async def mark_job_completed(job_id: str, db_pool: asyncpg.Pool) -> None:
        """
        Transitions the job to its terminal 'COMPLETED' state.

        Signifies the absolute conclusion of the MapReduce pipeline. No further
        state mutations or worker callbacks will be processed for this job ID.
        """
        query = "UPDATE public.jobs SET status = 'COMPLETED' WHERE id = $1"
        async with db_pool.acquire() as connection:
            await connection.execute(query, uuid.UUID(str(job_id)))
        logger.info("Job successfully marked as COMPLETED in database.")

    @staticmethod
    async def get_stalled_jobs(timeout_seconds: int, db_pool: asyncpg.Pool) -> List[str]:
        """
        Identifies active jobs exceeding the operational timeout threshold.

        This function supports the Orchestrator's Watchdog service. It executes a
        read-only sweep comparing the current database timestamp against the last
        recorded `updated_at` heartbeat to detect orphaned or deadlocked workloads.

        :param timeout_seconds: The threshold duration (in seconds) indicating a stall.
        :type timeout_seconds: int
        :param db_pool: The shared PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :return: A list of UUID strings representing jobs flagged for forceful reclamation.
        :rtype: List[str]
        """
        sweep_query = """
                      SELECT id
                      FROM public.jobs
                      WHERE status = 'RUNNING'
                        AND EXTRACT(EPOCH FROM (NOW() - updated_at)) > $1; \
                      """

        async with db_pool.acquire() as connection:
            # Execute a pure read-only query to prevent write-lock contention during sweeps
            records = await connection.fetch(sweep_query, timeout_seconds)

            if records:
                logger.warning("Watchdog sweep: %d stalled jobs detected.", len(records))

            return [str(record['id']) for record in records]

    @staticmethod
    async def mark_job_failed(job_id: str, db_pool: asyncpg.Pool) -> None:
        """
        Atomically transitions a job to the terminal 'FAILED' state.

        This method acts as the persistence mechanism for the Fail-Fast Protocol.
        It halts orchestration for a given job upon detecting unrecoverable infrastructure
        faults or terminal user-code exceptions (Poison Pills). Idempotent design ensures
        redundant failure signals do not overwrite existing terminal logs.
        """
        query = """
            UPDATE public.jobs
            SET status = 'FAILED'
            WHERE id = $1 
              AND status != 'FAILED';
        """
        async with db_pool.acquire() as connection:
            result = await connection.execute(query, uuid.UUID(str(job_id)))

        # Validate if the update mutated a row or if the job was already gracefully failed
        if result == "UPDATE 1":
            logger.error("Fail-Fast Protocol: Job %s forcefully transitioned to FAILED.", job_id)
        else:
            logger.debug("Job %s is already marked as FAILED. Skipping redundant update.", job_id)

    @staticmethod
    async def ping_job_activity(job_id: str, db_pool: asyncpg.Pool) -> None:
        """
        Registers a lightweight heartbeat timestamp to prevent premature Watchdog eviction.

        This method triggers a rapid, indexed `UPDATE` to refresh the `updated_at` column.
        To maintain database health, the caller (e.g., Task Consumer) should debounce
        these requests via distributed locks before invoking this persistence layer.
        """
        query = """
            UPDATE public.jobs
            SET updated_at = NOW()
            WHERE id = $1 
              AND status = 'RUNNING';
        """
        async with db_pool.acquire() as connection:
            await connection.execute(query, uuid.UUID(str(job_id)))

    @staticmethod
    async def get_job_recovery_context(job_id: str, pool: asyncpg.Pool) -> dict | None:
        """
        Retrieves the execution context required to surgically reconstruct a lost task.

        This function enables the Orchestrator's Reactive Lineage Recovery. It extracts
        the `user_id`, explicit `mapper_filename`, and `num_mappers` to perfectly mirror
        the original multi-tenant S3 boundaries and dynamic scaling parameters, allowing
        the system to re-provision isolated chunks without restarting the entire Job.
        """
        query = """
                SELECT user_id,
                       input_filename,
                       total_chunks,
                       num_reducers,
                       num_mappers,
                       mapper_filename
                FROM public.jobs
                WHERE id = $1;
                """
        async with pool.acquire() as conn:
            record = await conn.fetchrow(query, uuid.UUID(job_id))
            return dict(record) if record else None

    @staticmethod
    async def get_job_elapsed_time(job_id: str, db_pool: asyncpg.Pool) -> float:
        """
        Calculates the elapsed time since the job's last recorded heartbeat.

        Executes a read-only query to determine the eventual consistency gap for a
        given job. By extracting the raw SQL to the Data Access Layer (DAL), it
        prevents leaky abstractions in the Reconciler service and centralizes
        query optimization.

        :param job_id: The universally unique identifier (UUID) of the job.
        :type job_id: str
        :param db_pool: The shared, multiplexed PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :return: The elapsed time in seconds. Returns 0.0 if the job is not found.
        :rtype: float
        :raises ValueError: If the provided job_id cannot be cast to a valid UUID.
        """
        query = """
                SELECT EXTRACT(EPOCH FROM (NOW() - updated_at)) as elapsed
                FROM public.jobs
                WHERE id = $1; \
                """
        async with db_pool.acquire() as connection:
            # Execute a pure read-only query to prevent write-lock contention
            record = await connection.fetchrow(query, uuid.UUID(str(job_id)))

            return float(record['elapsed']) if record else 0.0

    @staticmethod
    async def get_job_status(job_id: str, db_pool: asyncpg.Pool) -> None | dict[Any, Any] | dict[str, Any] | dict[
        str, str] | dict[bytes, bytes]:
        """
        Retrieves the real-time execution status and progress metrics for a specific job.

        This read-only query fetches the essential lifecycle data required by the
        UI service to render job progress bars and status indicators.

        :param job_id: The universally unique identifier (UUID) of the job.
        :type job_id: str
        :param db_pool: The shared, multiplexed PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :return: A dictionary containing the job's status data, or None if not found.
        :rtype: Optional[Dict[str, Any]]
        """
        query = """
                SELECT id, status, completed_map_chunks, completed_reduce_chunks, created_at, updated_at
                FROM public.jobs
                WHERE id = $1 \
                """
        async with db_pool.acquire() as connection:
            record = await connection.fetchrow(query, uuid.UUID(str(job_id)))

            if not record:
                return None

            # Convert asyncpg Record to dict and cast UUID to string for API JSON serialization
            result = dict(record)
            result["id"] = str(result["id"])
            return result

    @staticmethod
    async def get_all_jobs_status(limit: int, offset: int, db_pool: asyncpg.Pool) -> List[Dict[str, Any]]:
        """
        Retrieves a paginated list of all MapReduce jobs and their execution statuses.

        :param limit: The maximum number of records to return.
        :type limit: int
        :param offset: The number of records to skip for pagination.
        :type offset: int
        :param db_pool: The shared, multiplexed PostgreSQL connection pool.
        :type db_pool: asyncpg.Pool
        :return: A list of dictionaries representing the job status records.
        :rtype: List[Dict[str, Any]]
        """
        query = """
                SELECT id, status, completed_map_chunks, completed_reduce_chunks, created_at, updated_at
                FROM public.jobs
                ORDER BY created_at DESC
                    LIMIT $1 \
                OFFSET $2 \
                """
        async with db_pool.acquire() as connection:
            records = await connection.fetch(query, limit, offset)

            results = []
            for record in records:
                rec_dict = dict(record)
                rec_dict["id"] = str(rec_dict["id"])
                results.append(rec_dict)

            return results