FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# Copy the exact Fat JAR name generated by Maven
COPY target/mapreduce-ess-1.0-SNAPSHOT-jar-with-dependencies.jar ess.jar

EXPOSE 7337
ENTRYPOINT ["java", "-jar", "ess.jar"]