services:
  # 1. PostgreSQL (For the Manager Service)
  postgres-service:
    image: postgres:15-alpine
    container_name: local-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DisSami2026!
      POSTGRES_DB: dds_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # --- Map the initialization script ---
      # This assumes mapreduce-node and mapreduce-manager are in the same parent folder (IdeaProjects)
      - ../mapreduce-manager/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

  # 2. MinIO (For both Manager and Worker)
  minio:
    image: minio/minio:latest
    container_name: local-minio
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      # Using the credentials expected by your Java Worker
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # 3. RabbitMQ (For both Manager and Worker)
  rabbitmq:
    image: rabbitmq:3-management
    container_name: local-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Web Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  # 4. Redis (For high-throughput phase barrier counting)
  local-redis:
    image: redis:7-alpine
    container_name: local-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  minio_data:
  rabbitmq_data: