# ==========================================
# STAGE 1: Build the Java Application & gRPC Stubs
# ==========================================
FROM maven:3.9-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy the parent pom.xml and the module poms
COPY pom.xml .
COPY mapreduce-core/pom.xml ./mapreduce-core/
COPY mapreduce-worker/pom.xml ./mapreduce-worker/

# Download dependencies (Cache layer)
RUN mvn dependency:go-offline -pl mapreduce-worker -am

# Copy the source code (This includes the .proto files in src/main/proto)
COPY mapreduce-core/src ./mapreduce-core/src
COPY mapreduce-worker/src ./mapreduce-worker/src

# Compile and package into a single Uber-JAR (executes protobuf-maven-plugin)
RUN mvn clean package -pl mapreduce-worker -am -DskipTests

# ==========================================
# STAGE 2: Create the Production Runtime Image
# ==========================================
# Switched from Alpine to standard JRE to support gRPC/Netty native C-bindings
FROM eclipse-temurin:17-jre
WORKDIR /app

# Copy the Uber-JAR generated by the maven-shade-plugin
COPY --from=builder /app/mapreduce-worker/target/mapreduce-worker-1.0-SNAPSHOT.jar app.jar

# Expose the Hybrid Networking Ports
EXPOSE 50051 8080

# Set default Environment Variables
ENV RABBITMQ_HOST="host.docker.internal"
ENV RABBITMQ_QUEUE="map_tasks_queue"
ENV MINIO_ENDPOINT="http://host.docker.internal:9000"
ENV MINIO_ROOT_USER="minioadmin"
ENV MINIO_ROOT_PASSWORD="minioadmin"

# Start the Worker Engine using the Uber-JAR
CMD ["java", "-XX:InitialRAMPercentage=50.0", "-XX:MaxRAMPercentage=75.0", "-jar", "app.jar"]