apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  serviceName: keycloak-discovery
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.5.6
        args: ["start"]
        env:
        # Hostname & Connectivity
        - name: KC_HOSTNAME
          value: "keycloak.192.168.49.2.nip.io" # For coenncting the CLI and the rest services (TODO: Put the the IP in a seperate file so that we can easily change it later at merging)
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_PROXY_HEADERS
          value: "xforwarded" 

        # Database
        - name: KC_DB
          value: "postgres"
        - name: KC_DB_URL_HOST
          value: "postgres-keycloak-service"
        - name: KC_DB_URL_DATABASE
          value: "keycloak"
        - name: KC_DB_USERNAME
          value: "keycloak"
        - name: KC_DB_PASSWORD
          value: "S71h2nd)e"

        # Admin Setup
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          value: "admin"
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          value: "admin"

        # Observability
        - name: KC_HEALTH_ENABLED
          value: "true"
        - name: KC_METRICS_ENABLED
          value: "true"

        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9000
          name: management

        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9000
          initialDelaySeconds: 40
          periodSeconds: 10
        
        resources:
          limits:
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1000Mi
