apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: "keycloak"
        - name: POSTGRES_USER
          value: "keycloak"
        - name: POSTGRES_PASSWORD
          value: "S71h2nd)e"
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak-service
spec:
  selector:
    app: postgres-keycloak
  ports:
  - port: 5432
    targetPort: 5432
