package com.iliasbolan.engine;

import com.iliasbolan.core.KeyValuePair;
import com.iliasbolan.core.Mapper;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.RecursiveTask;

/**
 * Executes the Map phase of a Map-Reduce job utilizing Java's Fork/Join Framework for
 * optimal intra-node parallelism.
 * <p>
 * According to the system architecture, the Manager Service assigns 64MB data chunks
 * to Worker nodes. To process this chunk efficiently, {@code MapTaskProcessor} recursively
 * splits the list of data records (e.g., lines of text) into smaller sub-tasks until
 * they fall below a defined {@link #THRESHOLD}. These sub-tasks are then processed
 * concurrently across the available CPU cores of the Kubernetes Pod.
 * </p>
 * <p>
 * Upon completion of the map operations, the caller is responsible for applying the
 * Shuffle partitioning logic (e.g., {@code hash(key) % R}) and writing the intermediate
 * files to the Shared File System (MinIO).
 * </p>
 *
 * @author Ilias Bolanakis
 * @version 1.0
 * @see java.util.concurrent.RecursiveTask
 * @see com.iliasbolan.core.Mapper
 * @since 2026-03-30
 */
public class MapTaskProcessor extends RecursiveTask<List<KeyValuePair>> {

    /** * The maximum number of records a single thread should process sequentially.
     * If the assigned workload exceeds this threshold, the task will be bifurcated.
     */
    private static final int THRESHOLD = 5000;

    /** The subset of data records (e.g., lines of a file) to be processed. */
    private final List<String> records;

    /** The starting index (inclusive) of the records list assigned to this specific task. */
    private final int start;

    /** The ending index (exclusive) of the records list assigned to this specific task. */
    private final int end;

    /** The dynamically loaded user-defined Mapper implementation. */
    private final Mapper mapper;

    /**
     * Constructs a new {@code MapTaskProcessor} for a specific segment of the data chunk.
     *
     * @param records The complete list of records parsed from the 64MB chunk.
     * @param start   The starting index for this task's segment.
     * @param end     The ending index for this task's segment.
     * @param mapper  The user's {@link Mapper} implementation dynamically loaded via Reflection.
     */
    public MapTaskProcessor(List<String> records, int start, int end, Mapper mapper) {
        this.records = records;
        this.start = start;
        this.end = end;
        this.mapper = mapper;
    }

    /**
     * The core computation method invoked by the {@link java.util.concurrent.ForkJoinPool}.
     * <p>
     * If the workload ({@code end - start}) is less than or equal to the {@link #THRESHOLD},
     * the records are processed sequentially using the user's {@link Mapper#map(String, String)} method.
     * Otherwise, the task is split into two equal sub-tasks: one is forked asynchronously,
     * and the other is computed immediately, after which their results are merged.
     * </p>
     *
     * @return A consolidated {@link List} of all intermediate {@link KeyValuePair} objects
     * generated by this task and its sub-tasks.
     */
    @Override
    protected List<KeyValuePair> compute() {
        int length = end - start;

        // Base case: workload is small enough to process sequentially
        if (length <= THRESHOLD) {
            return processSequentially();
        }

        // Recursive case: split the workload in half
        int middle = start + (length / 2);

        MapTaskProcessor leftTask = new MapTaskProcessor(records, start, middle, mapper);
        MapTaskProcessor rightTask = new MapTaskProcessor(records, middle, end, mapper);

        // Fork the left task to run asynchronously on another thread
        leftTask.fork();

        // Compute the right task immediately on the current thread
        List<KeyValuePair> rightResult = rightTask.compute();

        // Wait for the left task to complete and retrieve its result
        List<KeyValuePair> leftResult = leftTask.join();

        // Merge the intermediate results
        List<KeyValuePair> mergedResult = new ArrayList<>(leftResult);
        mergedResult.addAll(rightResult);

        return mergedResult;
    }

    /**
     * Iterates through the assigned segment of records and applies the user's Map logic.
     *
     * @return A {@link List} of intermediate {@link KeyValuePair} objects generated from this segment.
     */
    private List<KeyValuePair> processSequentially() {
        List<KeyValuePair> intermediateResults = new ArrayList<>();

        for (int i = start; i < end; i++) {
            String record = records.get(i);

            // In a standard text processing job, the key could be the line number or an offset.
            // For simplicity, we pass the line number as a String.
            String key = String.valueOf(i);

            // Invoke the user's custom map function
            List<KeyValuePair> mappedPairs = mapper.map(key, record);

            if (mappedPairs != null) {
                intermediateResults.addAll(mappedPairs);
            }
        }

        return intermediateResults;
    }
}