package com.iliasbolan.engine;

import com.iliasbolan.core.KeyValuePair;
import com.iliasbolan.core.Reducer;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.RecursiveTask;

/**
 * Executes the Reduce phase of a Map-Reduce job utilizing Java's Fork/Join Framework
 * for optimal intra-node parallelism.
 * <p>
 * According to the system architecture, after the Shuffle phase, intermediate data is
 * grouped by key. A Reducer Worker reads this grouped data from MinIO. To process it
 * efficiently, {@code ReduceTaskProcessor} recursively splits the grouped records
 * (represented as Map Entries) into smaller sub-tasks until they fall below a defined
 * {@link #THRESHOLD}. These sub-tasks are then processed concurrently across the
 * available CPU cores of the Kubernetes Pod.
 * </p>
 *
 * @author Ilias (Compute Engine Lead)
 * @version 1.0
 * @see java.util.concurrent.RecursiveTask
 * @see com.iliasbolan.core.Reducer
 * @since 2026-03-30
 */
public class ReduceTaskProcessor extends RecursiveTask<List<KeyValuePair>> {

    /** * The maximum number of distinct keys a single thread should process sequentially.
     * If the assigned workload exceeds this threshold, the task is bifurcated.
     */
    private static final int THRESHOLD = 1000;

    /** The grouped intermediate data, where each entry is a unique key and its list of values. */
    private final List<Map.Entry<String, List<String>>> groupedRecords;

    /** The starting index (inclusive) of the groupedRecords list assigned to this task. */
    private final int start;

    /** The ending index (exclusive) of the groupedRecords list assigned to this task. */
    private final int end;

    /** The dynamically loaded user-defined Reducer implementation. */
    private final Reducer reducer;

    /**
     * Constructs a new {@code ReduceTaskProcessor} for a specific segment of grouped data.
     *
     * @param groupedRecords The complete list of grouped records (Key -> List of Values).
     * @param start          The starting index for this task's segment.
     * @param end            The ending index for this task's segment.
     * @param reducer        The user's {@link Reducer} implementation loaded via Reflection.
     */
    public ReduceTaskProcessor(List<Map.Entry<String, List<String>>> groupedRecords, int start, int end, Reducer reducer) {
        this.groupedRecords = groupedRecords;
        this.start = start;
        this.end = end;
        this.reducer = reducer;
    }

    /**
     * The core computation method invoked by the {@link java.util.concurrent.ForkJoinPool}.
     * <p>
     * If the workload is less than or equal to the {@link #THRESHOLD}, the grouped records
     * are processed sequentially using the user's {@link Reducer#reduce(String, List)} method.
     * Otherwise, the task is split into two equal sub-tasks and processed in parallel.
     * </p>
     *
     * @return A consolidated {@link List} of all final {@link KeyValuePair} objects
     * generated by this task and its sub-tasks.
     */
    @Override
    protected List<KeyValuePair> compute() {
        int length = end - start;

        // Base case: workload is small enough to process sequentially
        if (length <= THRESHOLD) {
            return processSequentially();
        }

        // Recursive case: split the workload in half
        int middle = start + (length / 2);

        ReduceTaskProcessor leftTask = new ReduceTaskProcessor(groupedRecords, start, middle, reducer);
        ReduceTaskProcessor rightTask = new ReduceTaskProcessor(groupedRecords, middle, end, reducer);

        // Fork the left task to run asynchronously
        leftTask.fork();

        // Compute the right task immediately on the current thread
        List<KeyValuePair> rightResult = rightTask.compute();

        // Wait for the left task to complete
        List<KeyValuePair> leftResult = leftTask.join();

        // Merge the final results
        List<KeyValuePair> mergedResult = new ArrayList<>(leftResult);
        mergedResult.addAll(rightResult);

        return mergedResult;
    }

    /**
     * Iterates through the assigned segment of grouped records and applies the user's Reduce logic.
     *
     * @return A {@link List} of final {@link KeyValuePair} objects generated from this segment.
     */
    private List<KeyValuePair> processSequentially() {
        List<KeyValuePair> finalResults = new ArrayList<>();

        for (int i = start; i < end; i++) {
            Map.Entry<String, List<String>> entry = groupedRecords.get(i);

            // Invoke the user's custom reduce function for this key and its values
            KeyValuePair reducedResult = reducer.reduce(entry.getKey(), entry.getValue());

            if (reducedResult != null) {
                finalResults.add(reducedResult);
            }
        }

        return finalResults;
    }
}