package com.iliasbolan.core;

/**
 * The execution context used by Mappers to emit intermediate key-value pairs.
 * <p>
 * This interface decouples the Mapper logic from the underlying storage or
 * shuffling mechanism, allowing the engine to stream results directly to
 * disk or network buffers.
 * </p>
 *
 * @author Ilias Bolanakis
 * @version 1.0
 * @since 2026-04-27
 */
public interface Context {
    /**
     * Records an intermediate key-value pair generated by the Map phase.
     *
     * @param key   The intermediate key.
     * @param value The intermediate value.
     */
    void write(String key, String value);
}