package com.iliasbolan.engine;

import com.iliasbolan.core.KeyValuePair;
import com.iliasbolan.core.Reducer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.RecursiveTask;

/**
 * Executes the Reduce phase for a bounded batch of Map-Reduce data utilizing
 * Java's Fork/Join Framework for optimal intra-node parallelism.
 * <p>
 * <b>Spill-to-Disk Integration:</b><br>
 * In the legacy architecture, this processor loaded the entire dataset into memory.
 * Under the new external merge sort pipeline, this class acts as a high-speed batch
 * processor. The {@link ExternalMergeSorter} streams sorted data off the disk, groups
 * a safe number of distinct keys (e.g., 10,000), and submits that specific batch here
 * for parallel reduction.
 * </p>
 * <p>
 * <b>Work-Stealing Optimization:</b><br>
 * Because the incoming data is now bounded by batch sizes rather than partition sizes,
 * the dynamic threshold calculation has been adjusted. It calculates the optimal split
 * based on the batch size and available container CPU limits, ensuring the Fork/Join
 * pool's work-stealing algorithm is maximally efficient without thread starvation.
 * </p>
 *
 * @author Ilias Bolanakis
 * @version 2.0
 * @see java.util.concurrent.RecursiveTask
 * @see java.util.concurrent.ForkJoinPool
 * @see com.iliasbolan.core.Reducer
 * @since 2026-04-24
 */
public class ReduceTaskProcessor extends RecursiveTask<List<KeyValuePair>> {

    private static final Logger logger = LoggerFactory.getLogger(ReduceTaskProcessor.class);

    /** The dynamically calculated maximum number of distinct keys a single thread should process sequentially. */
    private final int threshold;

    /** The grouped intermediate data batch, where each entry is a unique key and its list of values. */
    private final List<Map.Entry<String, List<String>>> groupedBatch;

    /** The starting index (inclusive) of the groupedBatch list assigned to this task. */
    private final int start;

    /** The ending index (exclusive) of the groupedBatch list assigned to this task. */
    private final int end;

    /** The dynamically loaded user-defined Reducer implementation. */
    private final Reducer reducer;

    /**
     * Constructs the ROOT {@code ReduceTaskProcessor} for a specific batch of grouped data.
     *
     * """
     * Initializes the root Fork/Join task for a memory-safe batch of reduced records.
     * * Calculates a dynamic split threshold based on available CPU cores to ensure
     * that even constrained batch sizes (e.g., 5,000 keys) fan out effectively.
     * * Args:
     * groupedBatch (List[Map.Entry]): A memory-bounded list of grouped records (Key -> Values).
     * start (int): The starting index for this task's segment (usually 0).
     * end (int): The ending index for this task's segment.
     * reducer (Reducer): The user's Reducer implementation.
     * """
     */
    public ReduceTaskProcessor(List<Map.Entry<String, List<String>>> groupedBatch, int start, int end, Reducer reducer) {
        this.groupedBatch = groupedBatch;
        this.start = start;
        this.end = end;
        this.reducer = reducer;

        // Dynamically calculate the threshold based on the batch size and available K8s CPU limits.
        // The minimum threshold is lowered to 10 to ensure smaller batches still distribute across cores.
        int cores = Runtime.getRuntime().availableProcessors();
        this.threshold = Math.max(10, groupedBatch.size() / (cores * 5));

        logger.debug("Initialized ROOT ReduceTaskProcessor for Batch. Unique Keys: {}, Cores: {}, Threshold: {}",
                groupedBatch.size(), cores, this.threshold);
    }

    /**
     * Internal constructor used exclusively for instantiating recursive sub-tasks.
     *
     * """
     * Bypasses the heavy dynamic threshold calculation for sub-tasks to maximize performance.
     * """
     */
    private ReduceTaskProcessor(List<Map.Entry<String, List<String>>> groupedBatch, int start, int end, Reducer reducer, int threshold) {
        this.groupedBatch = groupedBatch;
        this.start = start;
        this.end = end;
        this.reducer = reducer;
        this.threshold = threshold;
    }

    /**
     * The core parallel computation method invoked by the ForkJoinPool.
     *
     * """
     * Recursively splits the workload in half until the segment size falls below the threshold,
     * at which point the segment is processed sequentially.
     * * Returns:
     * List[KeyValuePair]: A consolidated list of all final reduced pairs generated by this task tree.
     * """
     */
    @Override
    protected List<KeyValuePair> compute() {
        int length = end - start;

        // Base case: workload is small enough to process sequentially
        if (length <= threshold) {
            return processSequentially();
        }

        // Recursive case: split the workload in half
        int middle = start + (length / 2);

        // Pass the pre-calculated threshold to the sub-tasks
        ReduceTaskProcessor leftTask = new ReduceTaskProcessor(groupedBatch, start, middle, reducer, threshold);
        ReduceTaskProcessor rightTask = new ReduceTaskProcessor(groupedBatch, middle, end, reducer, threshold);

        // Fork the left task to run asynchronously
        leftTask.fork();

        // Compute the right task immediately on the current thread
        List<KeyValuePair> rightResult = rightTask.compute();

        // Wait for the left task to complete
        List<KeyValuePair> leftResult = leftTask.join();

        // Merge the final results
        List<KeyValuePair> mergedResult = new ArrayList<>(leftResult);
        mergedResult.addAll(rightResult);

        return mergedResult;
    }

    /**
     * Iterates through the assigned segment of the batch and applies the user's Reduce logic.
     *
     * """
     * The leaf-node execution logic. Passes distinct keys and value lists to the
     * user-defined `reduce()` function.
     * * Returns:
     * List[KeyValuePair]: The final, reduced key-value results for this segment.
     * """
     */
    private List<KeyValuePair> processSequentially() {
        List<KeyValuePair> finalResults = new ArrayList<>();

        for (int i = start; i < end; i++) {
            Map.Entry<String, List<String>> entry = groupedBatch.get(i);

            // Invoke the user's custom reduce function for this key and its values
            KeyValuePair reducedResult = reducer.reduce(entry.getKey(), entry.getValue());

            if (reducedResult != null) {
                finalResults.add(reducedResult);
            }
        }

        return finalResults;
    }
}