package com.iliasbolan.engine;

import com.iliasbolan.core.KeyValuePair;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Handles the Shuffle and Partitioning phase of a Map-Reduce job.
 * <p>
 * After the {@link MapTaskProcessor} generates a consolidated list of intermediate
 * {@link KeyValuePair} objects, this class is responsible for routing each pair to
 * its appropriate Reducer partition. It applies a deterministic hash function to the
 * key to calculate the target partition: <code>hash(key) % R</code>, where R is the
 * total number of Reducers.
 * </p>
 * <p>
 * <b>Peer-to-Peer (P2P) Architecture Update:</b><br>
 * Previously, this class utilized a Shared File System (MinIO/S3) for intermediate storage.
 * To support the high-performance P2P shuffle, this class now writes the partitioned
 * output directly to the local container disk using standard Java NIO. These deterministic
 * file paths (e.g., <code>/tmp/shuffle-data/{jobId}/{partitionId}/{mapTaskId}.txt</code>)
 * are subsequently exposed by the embedded worker HTTP server, allowing sibling
 * Reduce nodes to fetch the data directly over the network.
 * </p>
 *
 * @author Ilias Bolanakis
 * @version 2.0
 * @see com.iliasbolan.engine.MapTaskProcessor
 * @since 2026-03-30
 */
public class ShufflePartitioner {

    // Instantiate the SLF4J Logger specific to this class
    private static final Logger logger = LoggerFactory.getLogger(ShufflePartitioner.class);

    private final String baseShuffleDir;
    private final String jobId;
    private final String mapTaskId;
    private final int numReducers;

    /**
     * Constructs a new {@code ShufflePartitioner} for a specific Map task.
     *
     * @param baseShuffleDir  The root directory on the local disk for shuffle data (e.g., "/tmp/shuffle-data").
     * @param jobId           The unique identifier for the current Map-Reduce job.
     * @param mapTaskId       The unique identifier for the specific Map chunk being processed.
     * @param numReducers     The total number of Reducer partitions configured for this job (R).
     */
    public ShufflePartitioner(String baseShuffleDir, String jobId, String mapTaskId, int numReducers) {
        this.baseShuffleDir = baseShuffleDir;
        this.jobId = jobId;
        this.mapTaskId = mapTaskId;
        this.numReducers = numReducers;

        logger.info("Initialized ShufflePartitioner (P2P Local Storage). JobId: {}, MapTaskId: {}, Target Reducers: {}",
                jobId, mapTaskId, numReducers);
    }

    /**
     * Partitions a list of intermediate key-value pairs and writes them to the local disk.
     * <p>
     * This method executes the fundamental shuffle logic. It iterates through the provided
     * list, calculates the target partition using {@link Math#abs(int)} to prevent
     * negative modulo results, and groups the pairs. Finally, it formats each partition's
     * data into a simple text representation and persists it locally for the embedded server.
     * </p>
     *
     * @param intermediateData The complete list of key-value pairs generated by the Map phase.
     * @throws IOException If a file system error occurs during the directory creation or write process.
     */
    public void partitionAndWriteLocal(List<KeyValuePair> intermediateData) throws IOException {
        logger.info("Starting local partition and write phase. Total intermediate pairs to route: {}", intermediateData.size());

        // Step 1: Initialize in-memory buckets for each partition
        Map<Integer, List<KeyValuePair>> partitions = new HashMap<>();
        for (int i = 0; i < numReducers; i++) {
            partitions.put(i, new ArrayList<>());
        }

        // Step 2: Route each KeyValuePair using the record method pair.key()
        // PERFORMANCE CRITICAL: Absolutely no logging inside this loop!
        for (KeyValuePair pair : intermediateData) {
            // Use Math.abs to ensure the hash is positive before the modulo operation
            int partitionIndex = Math.abs(pair.key().hashCode()) % numReducers;
            partitions.get(partitionIndex).add(pair);
        }

        int writtenPartitionsCount = 0;

        // Step 3: Serialize and write each partition to the local container disk
        for (Map.Entry<Integer, List<KeyValuePair>> entry : partitions.entrySet()) {
            int partitionIndex = entry.getKey();
            List<KeyValuePair> partitionData = entry.getValue();

            // Skip empty partitions to save disk I/O and storage
            if (partitionData.isEmpty()) {
                logger.debug("Skipping partition {} as it contains no data.", partitionIndex);
                continue;
            }

            // Serialize data into a simple "key\tvalue\n" text format
            StringBuilder serializedData = new StringBuilder();
            for (KeyValuePair pair : partitionData) {
                serializedData.append(pair.key()).append("\t").append(pair.value()).append("\n");
            }

            // Generate the deterministic local file path for the embedded server to read from
            // Path structure: {baseDir}/{jobId}/{partitionIndex}/{mapTaskId}.txt
            Path partitionDir = Paths.get(baseShuffleDir, jobId, String.valueOf(partitionIndex));
            Path filePath = partitionDir.resolve(mapTaskId + ".txt");

            try {
                // Ensure the hierarchical directory structure exists before writing
                Files.createDirectories(partitionDir);

                // Write the string to disk, creating the file if missing, or overwriting if it exists
                Files.writeString(
                        filePath,
                        serializedData.toString(),
                        StandardOpenOption.CREATE,
                        StandardOpenOption.TRUNCATE_EXISTING
                );
                writtenPartitionsCount++;
            } catch (IOException e) {
                logger.error("Failed to write partition {} to local path: {}", partitionIndex, filePath.toAbsolutePath(), e);
                throw e;
            }
        }

        logger.info("Successfully completed Shuffle phase. Wrote {} active partitions to local disk.", writtenPartitionsCount);
    }
}