package com.iliasbolan.engine;

import com.iliasbolan.core.KeyValuePair;
import com.iliasbolan.storage.S3ClientService;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Handles the Shuffle and Partitioning phase of a Map-Reduce job.
 * <p>
 * After the {@link MapTaskProcessor} generates a consolidated list of intermediate
 * {@link KeyValuePair} objects, this class is responsible for routing each pair to
 * its appropriate Reducer partition. It applies a deterministic hash function to the
 * key to calculate the target partition: <code>hash(key) % R</code>, where R is the
 * total number of Reducers.
 * </p>
 * <p>
 * Once the data is grouped by partition in memory, it utilizes the {@link S3ClientService}
 * to write these partitioned files back to the Shared File System (MinIO) using
 * strictly deterministic S3 object paths to ensure idempotence.
 * </p>
 *
 * @author Ilias Bolanakis
 * @version 1.1
 * @see com.iliasbolan.engine.MapTaskProcessor
 * @see com.iliasbolan.storage.S3ClientService
 * @since 2026-03-30
 */
public class ShufflePartitioner {

    // Instantiate the SLF4J Logger specific to this class
    private static final Logger logger = LoggerFactory.getLogger(ShufflePartitioner.class);

    private final S3ClientService s3ClientService;
    private final String bucketName;
    private final String jobId;
    private final String mapTaskId;
    private final int numReducers;

    /**
     * Constructs a new {@code ShufflePartitioner} for a specific Map task.
     *
     * @param s3ClientService The active MinIO client service for uploading files.
     * @param bucketName      The destination bucket in MinIO.
     * @param jobId           The unique identifier for the current Map-Reduce job.
     * @param mapTaskId       The unique identifier for the specific Map chunk being processed.
     * @param numReducers     The total number of Reducer partitions configured for this job (R).
     */
    public ShufflePartitioner(S3ClientService s3ClientService, String bucketName, String jobId, String mapTaskId, int numReducers) {
        this.s3ClientService = s3ClientService;
        this.bucketName = bucketName;
        this.jobId = jobId;
        this.mapTaskId = mapTaskId;
        this.numReducers = numReducers;

        logger.info("Initialized ShufflePartitioner. JobId: {}, MapTaskId: {}, Target Reducers: {}",
                jobId, mapTaskId, numReducers);
    }

    /**
     * Partitions a list of intermediate key-value pairs and uploads them to MinIO.
     * <p>
     * This method executes the fundamental shuffle logic. It iterates through the provided
     * list, calculates the target partition using {@link Math#abs(int)} to prevent
     * negative modulo results, and groups the pairs. Finally, it formats each partition's
     * data into a simple text representation and uploads it to MinIO.
     * </p>
     *
     * @param intermediateData The complete list of key-value pairs generated by the Map phase.
     * @throws Throwable If an error occurs during the MinIO upload process.
     */
    public void partitionAndUpload(List<KeyValuePair> intermediateData) throws Throwable {
        logger.info("Starting partition and upload phase. Total intermediate pairs to route: {}", intermediateData.size());

        // Step 1: Initialize in-memory buckets for each partition
        Map<Integer, List<KeyValuePair>> partitions = new HashMap<>();
        for (int i = 0; i < numReducers; i++) {
            partitions.put(i, new ArrayList<>());
        }

        // Step 2: Route each KeyValuePair using the record method pair.key()
        // PERFORMANCE CRITICAL: Absolutely no logging inside this loop!
        for (KeyValuePair pair : intermediateData) {
            // Use Math.abs to ensure the hash is positive before the modulo operation
            int partitionIndex = Math.abs(pair.key().hashCode()) % numReducers;
            partitions.get(partitionIndex).add(pair);
        }

        int uploadedPartitionsCount = 0;

        // Step 3: Serialize and upload each partition
        for (Map.Entry<Integer, List<KeyValuePair>> entry : partitions.entrySet()) {
            int partitionIndex = entry.getKey();
            List<KeyValuePair> partitionData = entry.getValue();

            // Skip empty partitions to save MinIO I/O and storage
            if (partitionData.isEmpty()) {
                logger.debug("Skipping partition {} as it contains no data.", partitionIndex);
                continue;
            }

            // Serialize data into a simple "key\value\n" text format
            StringBuilder serializedData = new StringBuilder();
            for (KeyValuePair pair : partitionData) {
                serializedData.append(pair.key()).append("\t").append(pair.value()).append("\n");
            }

            // Generate the deterministic S3 object name (e.g., job_1/intermediate/map_1_part_0.txt)
            String objectName = String.format("%s/intermediate/%s_part_%d.txt", jobId, mapTaskId, partitionIndex);

            try {
                // Upload to MinIO
                // This now throws Throwable due to Resilience4j refactor
                s3ClientService.writeData(bucketName, objectName, serializedData.toString());
                uploadedPartitionsCount++;
            } catch (Throwable e) {
                logger.error("Failed to upload partition {} to MinIO path: {}", partitionIndex, objectName, e);
                throw e;
            }
        }

        logger.info("Successfully completed Shuffle phase. Uploaded {} active partitions.", uploadedPartitionsCount);
    }
}